import { TargetMatchBuffer, TargetReplaceBuffer, Insertion, Entry, RenderMap, ReservedWord } from '../../types';
export default class Parser {
    private static _loopKey;
    static __loopKey__: string;
    private static _renderKey;
    private static _partialKey;
    static __renderKey__: string;
    static __partialKey__: string;
    private static keyReggie;
    private static partialReggie;
    private static partialGroupReggie;
    static __CLOSE__: string;
    static LOOP_CLOSE: string;
    static LOOP_OPEN: (key: string) => string;
    private static DEPRECATED_TAGS;
    private static _delim;
    private static _loopSignature;
    private static _keySignature;
    private static _partialSignature;
    private static _replaceSignature;
    static hasPartial: (a: TargetMatchBuffer) => boolean;
    static partialIndex: (a: TargetMatchBuffer) => number;
    static matchPartials: (target: string) => RegExpMatchArray;
    static replacePartial: (a: TargetReplaceBuffer) => string;
    static hasKey: (a: TargetMatchBuffer) => boolean;
    static matchKeys: (target: string) => RegExpMatchArray;
    static hasLoop: (a: TargetMatchBuffer) => boolean;
    static matchLoops(target: string): string[];
    static replaceAnonLoopBuf: (a: TargetMatchBuffer) => string;
    static replacedNamedLoopBuf(copy: string, insert: Insertion | Entry): string;
    static hasSymbols(chunk: string): boolean;
    static ABT: ReservedWord[];
    static renderMap(content: string): RenderMap;
    static checkDeprecation(clone: string): void;
}
