"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AST_NESTED_KEYPARSE = exports.AST_CLOSE_LOOP_SCOPE = exports.AST_CLOSE_SCOPE = exports.AST_OPEN_SCOPE = exports.AST_LOOP_OPEN_REGGIE = exports.AST_RENDER_REGGIE = exports.AST_PARTIAL_REGGIE = exports.AST_LOOP_SIGNATURE = exports.AST_PARTIAL_SIGNATURE = exports.AST_RENDER_SIGNATURE = exports.AST_KEYSELF = exports.AST_TNC = exports.AST_TNO = exports.AST_KNC = exports.AST_KNO = exports.SELF = exports.AST_EQ = exports.AST_DT = void 0;
exports.AST_DT = '@';
exports.AST_EQ = '=';
exports.SELF = '_';
exports.AST_KNO = '(';
exports.AST_KNC = ')';
exports.AST_TNO = '{';
exports.AST_TNC = '}';
exports.AST_KEYSELF = `${exports.AST_TNO}${exports.SELF}${exports.AST_TNC}`;
exports.AST_RENDER_SIGNATURE = `${exports.AST_DT}render`;
exports.AST_PARTIAL_SIGNATURE = `${exports.AST_DT}partial`;
exports.AST_LOOP_SIGNATURE = `${exports.AST_DT}loop`;
exports.AST_PARTIAL_REGGIE = /<!--@partial=\w+[\w|\d|/\\]*-->/gi;
exports.AST_RENDER_REGGIE = /<!--@render=\w+.?[\w|\d|.]+-->/gi;
exports.AST_LOOP_OPEN_REGGIE = /<!--@loop\(\w+\){/gi;
exports.AST_OPEN_SCOPE = '<!--';
exports.AST_CLOSE_SCOPE = '-->';
exports.AST_CLOSE_LOOP_SCOPE = exports.AST_TNC + exports.AST_CLOSE_SCOPE;
exports.AST_NESTED_KEYPARSE = /{\w+.?[\w|\d]*}/gi;
//# sourceMappingURL=constants.js.map