export declare const AST_DT = "@";
export declare const AST_EQ = "=";
export declare const SELF = "_";
export declare const AST_KNO = "(";
export declare const AST_KNC = ")";
export declare const AST_TNO = "{";
export declare const AST_TNC = "}";
export declare const AST_KEYSELF: string;
export declare const AST_RENDER_SIGNATURE: string;
export declare const AST_PARTIAL_SIGNATURE: string;
export declare const AST_LOOP_SIGNATURE: string;
export declare const AST_PARTIAL_REGGIE: RegExp;
export declare const AST_RENDER_REGGIE: RegExp;
export declare const AST_LOOP_OPEN_REGGIE: RegExp;
export declare const AST_OPEN_SCOPE = "<!--";
export declare const AST_CLOSE_SCOPE = "-->";
export declare const AST_CLOSE_LOOP_SCOPE: string;
export declare const AST_NESTED_KEYPARSE: RegExp;
